= EZGL - An Easy Graphics Library

image:https://codedocs.xyz/mariobadr/ezgl.svg[link="https://codedocs.xyz/mariobadr/ezgl"]

EZGL is a C++ graphics library that provides a thin wrapper around GTK and Cairo,
making it easy to create GUI applications with 2D drawing support.
It is used by the https://github.com/verilog-to-routing/vtr-verilog-to-routing[VTR project] and as a teaching tool in ECE297.

== Dependencies

The library currently depends on GTK 3 and cairo.

== Compilation

This project uses CMake for compiling and requires CMake version 3.10 or higher.
CMake can configure the project for different build systems and IDEs (type `cmake --help` for a list of generators available for your platform).
We recommend you create a build directory before invoking CMake to configure the project (`cmake -B`).
For example, we can perform the configuration step from the project root directory:

  cmake -H. -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release
  cmake -H. -Bcmake-build-debug -DCMAKE_BUILD_TYPE=Debug

After the configuration step, you can ask CMake to build the project.

  cmake --build cmake-build-release/ --target all
  cmake --build cmake-build-debug/ --target all

=== Build Options

Build options can be found in `options.cmake`.
Simply specify the build option during the configuration step in CMake.
Using the already generated `cmake-build-release` directory from the previous section, we can:

  cmake -H. -Bcmake-build-release -DEZGL_BUILD_EXAMPLES=ON

Your IDE or Makefile should now include additional targets when you turn these options on.
For example, enabling `EZGL_BUILD_EXAMPLES` should provide access to the `basic-application` target, which you can build:

  cmake --build cmake-build-release/ --target basic-application
