name: Test

on:
  # Run the test whenenever there is a push to master to ensure that master
  # passes all of the build tests.
  push:
    branches:
      - master
  # Run on pull request to ensure the PR passes our CI before merging.
  pull_request:
  # Allow this workflow to be manually dispatched.
  workflow_dispatch:
  # Run this workflow on master daily.
  schedule:
  - cron: '0 0 * * *' # daily

# If this workflow is already running on a PR or branch, cancel it.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Build EZGL using default options on supported OSs.
  Build:
    name: 'B: Building EZGL'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
        build_type: ['release', 'debug']
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libgtk-3-dev libx11-dev

    - name: Build EZGL
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_COMPILE_WARNING_AS_ERROR=on
        cmake --build build/ --target all

  # Build EZGL with examples turned on to ensure they build as well.
  BuildExamples:
    name: 'Building Examples'
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libgtk-3-dev libx11-dev libxml2-utils

    - name: Build EZGL with examples
      run: |
        cmake -H. -Bbuild -DEZGL_BUILD_EXAMPLES=ON -DCMAKE_COMPILE_WARNING_AS_ERROR=on
        cmake --build build/ --target basic-application
